//
// Created by Zza on 2022/5/6.
//

#ifndef DATASTRUCTUREIMPLEMENTINGC_FOLYDALGORITHM_H
#define DATASTRUCTUREIMPLEMENTINGC_FOLYDALGORITHM_H

#include "../Graph.h"

bool Floyd(){
    return true;
}

#endif //DATASTRUCTUREIMPLEMENTINGC_FOLYDALGORITHM_H
