//
// Created by Zza on 2022/5/6.
//

#ifndef DATASTRUCTUREIMPLEMENTINGC_PRIMALGORITHM_H
#define DATASTRUCTUREIMPLEMENTINGC_PRIMALGORITHM_H

#include "../Graph.h"

#endif //DATASTRUCTUREIMPLEMENTINGC_PRIMALGORITHM_H
